package telegramgateway

import "context"

const methodSendVerificationMessage = "sendVerificationMessage"

// SendVerificationMessage sends a verification message with a code to the
// given phone number and returns the status of the created request.
//
// If req.RequestID comes from a previous CheckSendAbility call, the request
// is not charged a second time.
func (c *Client) SendVerificationMessage(
	ctx context.Context,
	req SendVerificationMessageRequest,
) (*RequestStatus, error) {
	var status RequestStatus
	if err := c.call(ctx, methodSendVerificationMessage, req, &status); err != nil {
		return nil, err
	}
	return &status, nil
}

const methodCheckSendAbility = "checkSendAbility"

// CheckSendAbility checks whether a verification message can be sent to the
// given phone number. The returned RequestStatus contains a RequestID that
// can be passed to SendVerificationMessage.
func (c *Client) CheckSendAbility(
	ctx context.Context,
	req CheckSendAbilityRequest,
) (*RequestStatus, error) {
	var status RequestStatus
	if err := c.call(ctx, methodCheckSendAbility, req, &status); err != nil {
		return nil, err
	}
	return &status, nil
}

const methodCheckVerificationStatus = "checkVerificationStatus"

// CheckVerificationStatus returns the current status of a verification
// message. If req.Code is set and the code was generated by Telegram, the
// result also tells whether the code is correct (see
// RequestStatus.VerificationStatus).
func (c *Client) CheckVerificationStatus(
	ctx context.Context,
	req CheckVerificationStatusRequest,
) (*RequestStatus, error) {
	var status RequestStatus
	if err := c.call(ctx, methodCheckVerificationStatus, req, &status); err != nil {
		return nil, err
	}
	return &status, nil
}

const methodRevokeVerificationMessage = "revokeVerificationMessage"

// RevokeVerificationMessage revokes a verification message that was sent
// earlier. It reports whether the message was revoked.
func (c *Client) RevokeVerificationMessage(
	ctx context.Context,
	req RevokeVerificationMessageRequest,
) (bool, error) {
	var isRevoked bool
	if err := c.call(ctx, methodRevokeVerificationMessage, req, &isRevoked); err != nil {
		return false, err
	}
	return isRevoked, nil
}
